package:
  name: menpofit
  version: {{ environ['CONDACI_VERSION'] }}

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - menpo 0.4.0
    - numpy 1.9.0
    - scipy 0.14.0
    - scikit-learn 0.15.2
    - wrapt 1.9.0

test:
  requires:
  - coverage
  - nose
  - mock

  imports:
  - menpo

  commands:
  - python -c "import nose; nose.main()" -s menpofit

about:
  home: https://github.com/menpo/menpofit/
  license: BSD
