package:
  name: menpofit
  version: {{ environ['CONDACI_VERSION'] }}

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - menpo >=0.5.1,<0.6
    - scikit-learn 0.16.*

test:
  requires:
  - coverage
  - nose
  - mock 1.0.1

  imports:
  - menpofit

about:
  home: https://github.com/menpo/menpofit/
  license: BSD
